app_name: "Wallety"

logging:
  structured-logging: true
  debuglevel: "deub"

recording:
  database: false
  csv: true

feature-flags:
  auth: false
  backup: false

service:
  port: 8087
  debug: true

# PSQL/SQLITE configration
db:
  variant: sqlite
  username: wallety
  dbname: wallet_store
  vendor:  
    sqlite:
      path: "local/db/"
    psql:
      host:
      port: